spring:
  profiles:
    active: "prod"
  datasource:
    url: jdbc:postgresql://localhost:5436/glygen
    username: glygen
    password: ENC(X0FzFsG1HA2ZepGQ2i//F9SMNcWJANlw6pLJtzy+JZo=)
    driver-class-name: org.postgresql.Driver
    separator: ^^^ END OF SCRIPT ^^^
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

glygen:
  scheme: http://
  host: localhost:8080
  basePath: /