spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/glygen
    username: glygen
    password: ENC(X0FzFsG1HA2ZepGQ2i//F9SMNcWJANlw6pLJtzy+JZo=)
    driver-class-name: org.postgresql.Driver
    separator: ^^^ END OF SCRIPT ^^^
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: glygenarray.api@gmail.com
    email: glygenarray.api@gmail.com
    password: ENC(jFt5gCSNcZv9uWa5yd+6gEFsZ6xmAu5pRkvdUgXY394=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

glygen:
  scheme: http://
  host: localhost:8080
  basePath: /
  frontend:
      scheme: http://
      host: localhost:3000
      basePath: /
      emailVerificationPage: emailConfirmation